project:
  type: website
  output-dir: docs

website:
  title: "Testing big ideas with simple methods"
  navbar:
    right:
      - cite.qmd
      - about.qmd
format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    theme: 
      light: flatly
      dark: solar
    css: styles.css
execute:
  freeze: auto



